
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import AppLayout from "@/app/(app)/layout";
import { ClientSideDateString } from "@/components/common/client-side-date-string";

export default function TermsOfServicePage() {
  return (
    <AppLayout>
      <div className="space-y-8">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="text-3xl text-glow-primary">Terms of Service</CardTitle>
            <CardDescription>Last Updated: <ClientSideDateString /></CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-foreground/90">
            <p>
              Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Lumina Images
              website and services (the "Service") operated by Lumina Images ("us", "we", or "our").
            </p>
            <p>
              Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
              These Terms apply to all visitors, users, and others who access or use the Service. By accessing or using
              the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may
              not access the Service.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">1. Accounts</h3>
            <p>
              When you create an account with us, you must provide us information that is accurate, complete, and current at all times.
              Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
              User authentication is provided by Clerk (clerk.com) and is subject to their terms.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">2. Use of the Service</h3>
            <p>
              Lumina Images grants you a non-exclusive, non-transferable, revocable license to use the Service for your personal, non-commercial use, or internal business use, strictly in accordance with these Terms.
            </p>
            <p>You agree not to use the Service:</p>
            <ul className="list-disc list-inside pl-4 space-y-1">
              <li>To generate illegal, harmful, defamatory, obscene, or infringing content.</li>
              <li>To violate any applicable national or international law or regulation.</li>
              <li>To impersonate or attempt to impersonate Lumina Images, a Lumina Images employee, another user, or any other person or entity.</li>
              <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or which, as determined by us, may harm Lumina Images or users of the Service or expose them to liability.</li>
              <li>To attempt to decompile or reverse engineer any software contained on the Service.</li>
            </ul>
             <p>The AI models used for image generation have their own safety filters. We are not responsible for content that may be blocked by these filters or for any limitations of the AI models.</p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">3. Content Ownership and Responsibility</h3>
            <p>
              You retain ownership of the prompts you submit to the Service. Subject to your compliance with these Terms, Lumina Images grants you ownership of the images generated by the Service based on your prompts ("Generated Images"), for any legal purpose, including commercial use.
            </p>
            <p>
              However, you are solely responsible for the prompts you provide and the Generated Images. You represent and warrant that your prompts and your use of Generated Images will not infringe upon the rights of any third party, including copyrights, trademarks, privacy, publicity, or other personal or proprietary rights.
            </p>
             <p>
              Lumina Images does not claim any ownership rights in the prompts you submit or the images generated for you. We may use prompts and Generated Images to improve our Service (e.g., for model training), but only in an anonymized and aggregated manner unless you explicitly consent otherwise.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">4. Intellectual Property</h3>
            <p>
              The Service and its original content (excluding content provided by users or generated for users), features, and functionality are and will remain the exclusive property of Lumina Images and its licensors.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">5. Termination</h3>
            <p>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">6. Limitation of Liability</h3>
            <p>
              In no event shall Lumina Images, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">7. Disclaimer</h3>
            <p>
              Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied.
              Lumina Images does not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">8. Changes to Terms</h3>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.
            </p>

            <h3 className="text-xl font-semibold text-glow-accent pt-4">9. Contact Us</h3>
            <p>
              If you have any questions about these Terms, please contact us at:
              legal@luminaimages.example.com (Not a real email)
            </p>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
